In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]

In [6]:
x = np.array(my_list)

In [12]:
x

array([1, 2, 3])

In [7]:
type(x)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
x2 = np.array(my_matrix)

In [10]:
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
type(x2)

numpy.ndarray

In [13]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [14]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
# Floating point zeros
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [24]:
# n.b. need n + 1 points for round numbers
np.linspace(0, 10, 51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# Uniform dist
np.random.rand(1)

array([0.87407059])

In [29]:
np.random.rand(5, 4)

array([[0.85740011, 0.02543626, 0.93421197, 0.03641869],
       [0.32205642, 0.66094491, 0.36647113, 0.02613017],
       [0.87761488, 0.84909224, 0.41313262, 0.73576647],
       [0.11781501, 0.58846916, 0.23346103, 0.02283083],
       [0.76012192, 0.1486731 , 0.80125132, 0.77300878]])

In [31]:
# Normal, there are a few alternatives as well
np.random.randn(5, 4)

array([[-1.35217277, -1.10549936, -1.12441079,  0.64164006],
       [-1.19341462, -0.5032545 ,  0.49951958,  0.53201596],
       [ 0.69918127, -0.86848466,  0.25751688,  0.20732964],
       [-0.07522177,  1.71411107,  0.48673344, -1.37912623],
       [ 0.60355038, -0.11346277, -0.76481295, -0.55915528]])

In [32]:
# [1, 100)
np.random.randint(1, 100, 10)

array([37, 96, 21, 31, 36, 59, 45, 94, 79, 89])

In [33]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.reshape(5, 4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [39]:
# 25 cols, 1 row
arr.shape

(25,)

In [41]:
# 25 rows, 1 col
arr.reshape(25, 1).shape

(25, 1)

In [42]:
arr.dtype

dtype('int64')

In [43]:
ranarr

array([10, 49,  9, 30,  8, 28, 17, 30,  9, 15])

In [46]:
ranarr.max()

49

In [47]:
ranarr.argmax()

1

In [48]:
ranarr.min()

8

In [49]:
ranarr.argmin()

4

In [50]:
arr = np.arange(0, 10)

In [51]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [53]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr / arr

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [55]:
1 / arr

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [58]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [60]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [61]:
np.max(arr)

9

In [62]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [63]:
arr = np.arange(0, 11)

In [64]:
arr[8]

8

In [65]:
arr[1:5]

array([1, 2, 3, 4])

In [66]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
# 'broadcasting', can't do for normal python lists
arr[0:5] = 100

In [68]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [69]:
arr = np.arange(0, 11)
slice_of_arr = arr[0:6]

In [70]:
slice_of_arr[:] = 99

In [73]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [74]:
# modified because slice is just a pointer, more memory efficient
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr_copy = arr.copy()

In [76]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [77]:
arr_copy[:] = 200

In [79]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [80]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [81]:
# mat[row, col]
# mat[row][col]
mat = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [82]:
mat[0]

array([ 5, 10, 15])

In [83]:
mat[1, 1]

25

In [84]:
mat[1][1]

25

In [85]:
mat[0,2]

15

In [86]:
mat[:2, 1:]

array([[10, 15],
       [25, 30]])

In [87]:
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [88]:
# CONDITIONAL SELECTION

In [92]:
arr = np.arange(1, 11)

In [93]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [94]:
bool_arr = arr > 4

In [95]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [97]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [98]:
arr[arr <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])